### ISSUE TITLE
How to manage multiple video sources using only 2 controllers?

### ISSUE THREAD

**Issue by aytunch** [brownsoo/flutter_video_list_sample#5]
I see that you are using only one controller in play_page and replacing the data source/url without creating a new controller. Do you know if there are no memory leaks with this strategy? It looks very smart but I see many issues on GitHub for video_player which state crashes after 15 videos or some time passes playing.

I want to have a video feed pageview just like TikTok. And I want to preload the next video before user swipes screen. So I need 2 controllers. 1 is current_controller(cont1) the other 1 is next_controller(cont2). I want to use something similar to what you did in play_page but I am stuck.

cont1 will point to data source vid1 and will autoplay.
cont2 will point to data source vid2 and will be in paused state.
Once the user swipes to vid2, cont1 will point to data source vid3 and will be in paused state and so on..
This way hopefully we will have no memory issues AND only be using 2 controllers AND not make the user wait for the current videos initializing.

cont1 -> vid1
cont2 -> vid2
cont1 -> vid3
cont2 -> vid4
cont1 -> vid5
cont2 -> vid6
....

Do you think we can use your code to implement this use case?

Thank you very much for this repo and your work:D

**Comment by brownsoo** [comment]
Hello, @aytunch

My code uses new controller for every video start. You can see creating new controller in this function.
```
void _initializeAndPlay(int index) async
```

In my case, one StatefulWidget  works with many video files so I used a new controller per a video. The controller must be disposed if there is no more need for memory leaks.


In your case, I think a page of PageView needs a controller because each page plays single video. When the page build, controller initialize and pause video. When the page is current page of PageView, controller plays video.

Sorry for long long delayed reply.
Thank you.
